/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package local.javaredes;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Paulo Santos
 */
public class FormCliente1ComThread extends javax.swing.JFrame {

    
    /**
     * Creates new form FormCliente
     */
    public FormCliente1ComThread() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloNome = new javax.swing.JLabel();
        labelNome = new javax.swing.JTextField();
        rotuloIdade = new javax.swing.JLabel();
        labelIdade = new javax.swing.JTextField();
        rotuloRetornoServidor = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        servidorResposta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotuloNome.setText("Nome");

        labelNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelNomeActionPerformed(evt);
            }
        });

        rotuloIdade.setText("Idade");

        labelIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelIdadeActionPerformed(evt);
            }
        });

        rotuloRetornoServidor.setText("Retorno do Servidor");

        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        servidorResposta.setEditable(false);
        servidorResposta.setColumns(20);
        servidorResposta.setRows(5);
        jScrollPane2.setViewportView(servidorResposta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(labelIdade)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotuloNome)
                            .addComponent(rotuloIdade)
                            .addComponent(rotuloRetornoServidor)))
                    .addComponent(jScrollPane2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rotuloNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotuloIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rotuloRetornoServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelIdadeActionPerformed

    private void labelNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelNomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_labelNomeActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
    
        int idade = validarIdade();
        if(idade != -1){
            inserePessoa();
        }
        
    }//GEN-LAST:event_botaoEnviarActionPerformed

    public void inserePessoa(){
            
         SwingUtilities.invokeLater(new Runnable(){
                @Override
                public void run() {
                    new Thread(
                            new ThreadCliente(
                            labelNome.getText(), 
                            Integer.parseInt(labelIdade.getText()),
                            servidorResposta)
                    ).start();
                }       
              
            }
        );
      
        
    }
    
    public int validarIdade(){
        
        int idade = -1;
        
        boolean idadeValida = false;
        try{
            while(!idadeValida){

                String entrada = labelIdade.getText();
                if(entrada == null || entrada.trim().isEmpty()){
                    JOptionPane.showMessageDialog(
                            null, 
                            "Idade não pode ficar em branco.", 
                            "Valor Inválido", 
                            HEIGHT
                    );
                    return -1;
                }

                idade = Integer.parseInt(entrada);
                if(idade <= 0 || idade > 120){
                    JOptionPane.showMessageDialog(
                            null, 
                            "Digite a idade correta.", 
                            "Valor Inválido", 
                            HEIGHT
                    );
                    labelIdade.setText("");
                } else {
                    idadeValida = true;
                }
            }
        
        }catch (NumberFormatException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Digite a idade correta.", "Valor Inválido", HEIGHT);
        }
        
        return idade;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente1ComThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente1ComThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente1ComThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente1ComThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
               FormCliente1ComThread frame = new FormCliente1ComThread();
               frame.setVisible(true);
               frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField labelIdade;
    private javax.swing.JTextField labelNome;
    private javax.swing.JLabel rotuloIdade;
    private javax.swing.JLabel rotuloNome;
    private javax.swing.JLabel rotuloRetornoServidor;
    private javax.swing.JTextArea servidorResposta;
    // End of variables declaration//GEN-END:variables
}
